### ISSUE TITLE
Blank Export Page

### ISSUE THREAD

**Issue by clmazzac** [wildstang/WildRank#243]
![image](https://user-images.githubusercontent.com/94644024/227673889-c67d91dd-ed97-4e8f-81da-baa2708bb6e9.png)
We've been getting this "Cache is not defined" error while exporting data using WildRank on some machines. We've tried switching browsers, but on some machines the page is entirely blank except for the header. It works on my machine on Microsoft Edge, but on Microsoft Edge on some other machines it throws this error, along with Firefox and Chrome.

**Comment by fruzyna** [comment]
WildRank utilizes the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) to store the app for offline use. Most modern browsers only support the caches API when the connection is secure (HTTPS/SSL/TLS) or on localhost. This is likely why it doesn't work in the provided "screenshot", which appears to be connecting to a remote machine using plain HTTP, but it does work on another machine, which I'm assuming is hosting the server (localhost). While WildRank does require caches for some features, this (and probably other) pages shouldn't completely break because the connection is not compatible. I'll take a look this weekend, but this is probably an off-season bug fix.
